---
title: "Decision Factors"
author: "Sisun Cheng, Kristin Chang, Jenna Epstein"
date: "04/05/2022"
output:
  html_document:
    toc: yes
    toc_float: TRUE
    code_folding: hide
editor_options:
  chunk_output_type: inline
---
# 0. Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, results = FALSE, message = FALSE)
```

```{r libraries, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(sf)
library(lubridate)
library(tigris)
library(tidycensus)
library(gganimate)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(RSocrata)
library(caret)
library(purrr)
library(FNN)
library(stargazer)
library(dplyr)
library(spatstat)
library(raster)
library(spdep)
library(grid)
library(mapview)
library(stringr)
library(ggcorrplot)
library(scales)
library(colorspace)
library(rgdal)          
library(RColorBrewer) 
library(rasterVis)    
library(sp)
library(ggpubr)
library(leaflet)
library(gganimate)
library(gifski)
library(transformr)
library(jtools)
library(stringr)

library(randomForest)
library(e1071)  # SVM
library(xgboost)
library(readr)
library(car)

palette_5 <- c("#0c1f3f", "#08519c", "#3bf0c0", "#e6a52f", "#e76420")
palette_5blues <-c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c")
palette_4 <-c("#08519c","#3bf0c0","#e6a52f","#e76420")
palette_2 <-c("#e6a52f","#08519c")
palette_3 <-c("#e6a52f","#08519c", "#e76420")

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

```{r add plot and map themes for default visualizations, message=FALSE, warning=FALSE}
mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 16,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.text.x = element_text(size = 14))
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 16,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

```

# Load data from modeling rmd for crash and waze data

```{r PCI 2018}
load("Data/EPCenterline_new6.RData")

PCI2018 <- EPCenterline_new6%>%
  dplyr::select(PCI_2018)%>%
  st_as_sf()%>%
  st_transform(4326)

#writing out the file as a geojson
#st_write(PCI2018, "PCI2018.geojson", driver="GeoJSON")
```

# Load equity layer

```{r equity layer}
EquityLayer <- st_read("ApplicationDevelopment/AppData/EquityLayer/Equity_12_11_2020/Equity_12_11_2020.shp")%>%
  st_as_sf()%>%
  st_transform('ESRI:102339')%>%
  dplyr::select('Total_Equi')%>%
  mutate("total_equity" = Total_Equi)%>%
  dplyr::select('total_equity')

EquityLayer <- EquityLayer %>%
  st_transform(4326)

#st_write(EquityLayer, "EquityLayer.geojson", driver = "GeoJSON")
```


```{r crash layer}
#read in blank hex layer
BlankHex <- st_read("ApplicationDevelopment/AppData/BlankHex.shp")%>%
  st_as_sf()%>%
  st_transform('ESRI:102339')%>%
  mutate(HexID = row_number())

#read in crash point data
crashes <- st_read("Data/CRIS2021/CRIS2021.shp")%>%
  st_as_sf()%>%
  st_transform('ESRI:102339')%>%
  na.omit()

#join layers
crashHex <- st_join(crashes, BlankHex, join=st_within)%>%
  st_drop_geometry()%>%
  group_by(HexID)%>%
  summarize(crash_count = n())%>%
  full_join(BlankHex, by = "HexID")%>%
  drop_na(HexID)%>% #some NAs because 97 points are on the city border...excluding for now
  st_as_sf()%>%
  st_transform('ESRI:102339')
```


```{r traffic layer}
#read in waze data
waze <- st_read("Data/cleaned_waze_data.csv")%>%
  filter(grepl('2021', Date))%>%
  st_as_sf(coords = c("x_coor", "y_coor"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102339')

#join to crashHex
crash_waze_Hex <- st_join(waze, crashHex, join=st_within)%>%
  st_drop_geometry()%>%
  group_by(HexID)%>%
  summarize(waze_count = n())%>%
  full_join(crashHex, by = "HexID")%>%
  drop_na(HexID)%>%
  st_as_sf()%>%
  st_transform('ESRI:102339')

#replace NAs with 0
crash_waze_Hex[is.na(crash_waze_Hex)] = 0
```


```{r all layers}
#transform equity data to have matching crs
EquityLayer_EPcrs <- EquityLayer %>%
  mutate(HexID = row_number())%>%
  st_drop_geometry()

#join to blank hex for same HexID col
allHex <- full_join(crash_waze_Hex, EquityLayer_EPcrs, by="HexID")%>%
  dplyr::select('HexID', 'waze_count', 'crash_count', 'total_equity', 'geometry')

#transform to 4326 for geojson
allHex <- allHex%>%
  st_transform(4326)

#write out as geojson
#st_write(allHex, "allHex.geojson", driver = "GeoJSON" )
```


```{r PCI 2021}
load("ApplicationDevelopment/AppData/EP_model_predictions_2021.RData")

#selecting streetnames
streetNames <- EPCenterline_new6 %>%
  dplyr::select('index','StreetName_EP','STYPE')%>%
  st_drop_geometry()

#selecting predictions
PCI2021 <- EP_model_predictions_2021%>%
  dplyr::select(predictions)%>%
  st_drop_geometry()

#join
PCI2021 <- full_join(EP_model_predictions_2021, streetNames, by='index')%>%
  st_as_sf()%>%
  st_transform(4326)

#select columns we want in tooltip
PCI2021 <- PCI2021%>%
  mutate(STREETNAME = StreetName_EP,
         PCI_2021 = predictions)%>%
  dplyr::select('STREETNAME','STYPE','CLASS','PLANAREA','DISTRICT','PCI_2021')

#concatenate STREETNAME and STYPE columns
PCI2021 <- PCI2021%>%
  unite('Merged', STREETNAME:STYPE, remove=FALSE)%>%
  mutate(STREETNAME=Merged)%>%
  dplyr::select('STREETNAME','CLASS','PLANAREA','DISTRICT','PCI_2021')

#writing out the file as a geojson
st_write(PCI2021, "PCI2021_predictions.geojson", driver="GeoJSON")

```













