---
title: "El_Paso_exploratory_analysis"
author: "Sisun Cheng"
date: "2022/1/22"
output:
  html_document:
    toc: yes
    toc_float: TRUE
    code_folding: hide
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, results = FALSE, message = FALSE)
```


```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(lubridate)
library(tigris)
library(tidycensus)
library(gganimate)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(RSocrata)
library(caret)
library(purrr)
library(FNN)
library(stargazer)
library(dplyr)
library(spatstat)
library(raster)
library(spdep)
library(grid)
library(mapview)
library(stringr)

palette5 <- c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c")
palette4 <- c("#D2FBD4","#92BCAB","#527D82","#123F5A")
palette4_2 <- c("#83c8f9","#2984c3","#075d9a","#000066")
palette2 <- c("#6baed6","#08519c")

```
```{r add plot and map themes for default visualizations, message=FALSE, warning=FALSE}
mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 16,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.text.x = element_text(size = 14))
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 16,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

```


```{r load data sources in github repo, warning=FALSE}
# Projection CRS: ESRI 102339 (NAD_1983_HARN_StatePlane_Texas_Central_FIPS_4205).
# Spatial unit: meter.
CIP_layer <- st_read("Data/Resurfacing/CIP_PRogram_Master_Layer.shp") %>%
  st_transform('ESRI:102339')

center_line <- st_read("Data/PCI_Study/Centerline_with_Age.shp") %>%
  st_transform('ESRI:102339')

EPCenterline <- st_read("Data/Penn/EPCenterline.shp") %>%
  st_transform('ESRI:102339')

zoning <- st_read("Data/Penn/Zoning.shp") %>%
  st_transform('ESRI:102339')

# Saved as .csv from file 'POTHOLES2013_2021.xls'
pot_holes <- read_csv("Data/POTHOLES2013_2021.csv")

# Sheet 'Waze for Cities Data _ Key Aler' saved as .csv from file 'Waze for Cities Data _ Key Alerts Dashboard_Traffic Alerts_Table.xlsx'
waze_data <- read_csv("Data/Waze for Cities Data3.csv")

VMT <- read_csv("Data/ElPaso_VMT_res_bg.csv")

```
The "el_paso_pass2" shapefile is too large for our GitHub repository, so load read in the file locally (download from our Google Drive). Only run one of the three code chunks below assigned to your name.
```{r load el_paso_pass2 data from local computer file path - SISUN}
elpaso_pass <- st_read("Data/PCI_Study/elpaso_pass2.shp") %>%
  st_transform('ESRI:102339')

```

```{r load el_paso_pass2 data from local computer file path - JENNA}
#JENNA - local file path
#elpaso_pass <- st_read("Data_JennaLocal/elpaso_pass2/elpaso_pass2.shp") %>%
#  st_transform('ESRI:102339')
```

```{r load el_paso_pass2 data from local computer file path - KRISTIN}
# KRISTIN - add your local path here
```

Boundary data of El Paso County downloaded from [Texas Open Data Portal](https://data.texas.gov/dataset/Texas-Counties-Map/48ag-x9aa).

```{r boundary data of El Paso county and city}
texas <-
  st_read("Data/TexasCountiesMap.geojson")

El_Paso <-
  texas %>%
  filter(name=='El Paso') %>%
  st_as_sf(coords = the_geom.coordinates, crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102339')

El_Paso_city <-
  st_read("Data/TxDOT_City_Boundaries.geojson") %>%
  filter(CITY_NM=='El Paso') %>%
  st_transform('ESRI:102339')

#ggplot() +
#  geom_sf(data = El_Paso_city, fill="grey") +
#  mapTheme()

```
```{r read in el paso city boundary}
El_Paso_city <-
  st_read("Data/TxDOT_City_Boundaries.geojson") %>%
  filter(CITY_NM=='El Paso') %>%
  st_transform('ESRI:102339')
```

## El Paso Demographics (Race, Ethnicity, Age data from 2019 5yr ACS)

```{r census_api_key_SISUN}
census_api_key("e79f3706b6d61249968c6ce88794f6f556e5bf3d", overwrite = TRUE)
```

```{r census_api_key_JENNA}
census_api_key("41e1c0d912341017fa6f36a5da061d3b23de335e", overwrite = TRUE)
```

```{r census_api_key_KRISTIN}
census_api_key("", overwrite=TRUE)
```

```{r census_demographics}
# census data

#variable list for ACS 2019 5 year data
ACSvar <- load_variables(year = 2019, dataset = "acs5", cache = TRUE)

#loading race data by tract - use E variables for estimate values
EP_race <-
  get_acs(geography = "tract",
          variables = c("B01003_001E", #total_pop
                        "B02001_002E", #white alone
                        "B02001_003E", #black or african american
                        "B02001_004E", #american indian or alaska native
                        "B02001_005E", #asian alone
                        "B02001_006E", #native hawaiian or pacific islander
                        "B02001_007E", #some other race
                        "B02001_008E"), #two or more races
          year = 2019,
          state = 48,      # 48 for Texas
          geometry = TRUE,
          county = 141,    # 141 for El Paso county
          output = "wide") %>%
  rename(total_pop =  B01003_001E,
         white = B02001_002E,
         black = B02001_003E,
         NAT = B02001_004E,
         asian = B02001_005E,
         PI = B02001_006E,
         other = B02001_007E,
         two_plus = B02001_008E) %>%
  dplyr::select("GEOID","NAME","total_pop","white","black","NAT","asian","PI","other","two_plus","geometry")%>% #drop MOE columns
  mutate(pctWhite = white/total_pop*100,
         pctBlack = black/total_pop*100,
         pctNAT = NAT/total_pop*100,
         pctAsian = asian/total_pop*100,
         pctPI = PI/total_pop*100,
         pctOther = other/total_pop*100,
         pctTwo_plus = two_plus/total_pop*100)

#loading ethnicity data by tract - use E variables for estimate values
EP_ethnicity <-
  get_acs(geography = "tract",
          variables = c("B01003_001E", #total_pop
                        "B03001_002E", #not hispanic or latino
                        "B03001_003E"), #hispanic or latino
          year = 2019,
          state = 48,
          geometry = TRUE,
          county = 141,
          output = "wide") %>%
  rename(total_pop =  B01003_001E,
         notHL = B03001_002E,
         HL = B03001_003E) %>%
  dplyr::select("GEOID","NAME","total_pop","notHL","HL","geometry")%>% #drop MOE columns
  mutate(pctNotHL = notHL/total_pop*100,
         pctHL = HL/total_pop*100)
```


```{r census_demographics_age}
#loading age data by tract - use E variables for estimate values
ageVar <- ACSvar %>%
  filter(concept=="SEX BY AGE")

ageVar <- ageVar %>% dplyr::select(name)

ageVar <- as.list(ageVar$name)%>%
  paste0("E")

EP_age <-
  get_acs(geography = "tract",
          variables = ageVar,
          year = 2019,
          state = 48,
          geometry = TRUE,
          county = 141,
          output = "wide")%>%
  dplyr::select("GEOID","NAME",all_of(ageVar),"geometry")

```
```{r census_age_var_labels}
ageVarLabels <- ACSvar %>%
  filter(concept=="SEX BY AGE")

ageVarLabels <- ageVarLabels %>% dplyr::select(name,label)

ageVarLabels$name <- ageVarLabels$name %>%
  paste0("E")

ageVarLabels$label <-gsub("!!", "", as.character(ageVarLabels$label))
ageVarLabels$label <-gsub("Estimate", "", as.character(ageVarLabels$label))
ageVarLabels$label <-gsub(":", "_", as.character(ageVarLabels$label))


ageVarLabels <- ageVarLabels %>% dplyr::rename(VAR_NAME = name)
ageVarLabels <- ageVarLabels %>% dplyr::rename(LABEL = label)


# COMMENTING OUT BELOW TESTING (JENNA)
#transposing, in case it is needed
#ageVarLabels_new <- ageVarLabels %>%
#  pivot_longer(!VAR_NAME, names_to = "col1", values_to = "col2") %>%
#  pivot_wider(names_from = "VAR_NAME", values_from = "col2")

#renaming by matching - test
#names(EP_age) <- ageVarLabels$LABEL[match(names(EP_age), ageVarLabels$VAR_NAME)]

```


```{r census_age_var_rename_match}
EP_age_new <- EP_age %>%
      rename_at(as.vector(na.omit(ageVarLabels$VAR_NAME[match(names(EP_age), ageVarLabels$VAR_NAME)])),
               ~as.vector(na.omit(ageVarLabels$LABEL[match(names(EP_age), ageVarLabels$VAR_NAME)])))
```

```{r census_demo_age_charts}
# transform data to long
EP_age_long <- EP_age_new%>%
  gather(variable, value, -geometry, -GEOID, -NAME)

# new column for sex
EP_age_long <- EP_age_long %>%
  dplyr::mutate(Sex=
                  case_when(
                    str_detect(EP_age_long$variable, "Male") ~ "Male",
                    str_detect(EP_age_long$variable, "Female") ~ "Female",
                        TRUE ~ "Total"))

EP_age_long_nototal<-EP_age_long[!(EP_age_long$Sex=="Total" | EP_age_long$variable=="Total_Male_" | EP_age_long$variable=="Total_Female_"),]


ggplot(EP_age_long_nototal, aes(x = value, y = variable, fill = Sex)) +
  geom_col() + plotTheme()
```

```{r census_demo_maps}
#plotting census demographics data
#race map

race_long <- EP_race%>%
  dplyr::select(GEOID,NAME, pctWhite, pctBlack, pctNAT, pctAsian, pctPI, pctOther, pctTwo_plus)%>%
  gather(variable, value, -geometry, -GEOID, -NAME)

race_vars <- unique(race_long$variable)
mapList <- list()

for(i in race_vars){
  mapList[[i]] <-
    ggplot() +
      geom_sf(data = filter(race_long, variable == i), aes(fill=value), colour=NA) +
      scale_fill_viridis(name="") +
      labs(title=i) +
      mapTheme()}

do.call(grid.arrange,c(mapList, ncol = 4, top = "Race by Census Tract"))

```

```{r census_demo_maps2}
#ethnicity map - Hispanic or Latino
ggplot()+
  geom_sf(data=EP_ethnicity, aes(fill=pctHL))+
  scale_fill_viridis()+
  labs(title="Percent Hispanic or Latino in 2019",
       subtitle="Census Tracts in El Paso, TX",
       caption = "Source: US Census, ACS 2019") + mapTheme()

```
## El Paso Socioeconomics (data from 2019 5yr ACS)
```{r}

EP_econ <-
  get_acs(geography = "tract",
          variables = c("B19013_001E", #median household income
                        "B25058_001E", #median rent
                        "B08301_001E", #people who have means of transportation to work
                        "B01003_001E"), #total pop
          year = 2019,
          state = 48,      # 48 for Texas
          geometry = TRUE,
          county = 141,    # 141 for El Paso county
          output = "wide") %>%
  rename(total_pop =  B01003_001E,
         med_hh_income = B19013_001E,
         med_rent = B25058_001E,
         transport_to_work = B08301_001E) %>%
  dplyr::select("GEOID","NAME","total_pop","med_hh_income","med_rent","transport_to_work","geometry")%>% #drop MOE columns
  mutate(pct_transport_to_work = (ifelse(total_pop > 0, transport_to_work / total_pop,0))*100)
```
```{r census_socioecon_maps}
econ_long <- EP_econ%>%
  dplyr::select(GEOID,NAME, med_hh_income, med_rent, pct_transport_to_work)%>%
  gather(variable, value, -geometry, -GEOID, -NAME)

econ_vars <- unique(econ_long$variable)
mapList_econ <- list()

for(i in econ_vars){
  mapList_econ[[i]] <-
    ggplot() +
      geom_sf(data = filter(econ_long, variable == i), aes(fill=value), colour=NA) +
      scale_fill_viridis(name="") +
      labs(title=i) + mapTheme()
      }

do.call(grid.arrange,c(mapList_econ, ncol = 3, top = "Select Socioeconomics by Census Tract", bottom = "Source: US Census, ACS 2019"))
```
```{r census_socioecon_transport_map}
#pct transport to work map
ggplot()+
  geom_sf(data=EP_econ, aes(fill=pct_transport_to_work))+
  scale_fill_viridis()+
  labs(title="Percent Population with Transportation to Work in 2019",
       subtitle="Census Tracts in El Paso, TX", caption="Source: US Census, ACS 2019") + mapTheme()
```
```{r census_socioecon_medhhinc_map}
#median household inc map
ggplot()+
  geom_sf(data=EP_econ, aes(fill=med_hh_income))+
  scale_fill_viridis()+
  labs(title="Median Household Income 2019",
       subtitle="Census Tracts in El Paso, TX", caption="Source: US Census, ACS 2019") + mapTheme()
```

```{r census_socioecon_medrent_map}
#median rent map
ggplot()+
  geom_sf(data=EP_econ, aes(fill=med_rent))+
  scale_fill_viridis()+
  labs(title="Median Rent ($) 2019",
       subtitle="Census Tracts in El Paso, TX", caption="Source: US Census, ACS 2019") + mapTheme()
```


```{r process the waze data 1}
x_fin <- data.frame()
y_fin <- data.frame()

for (i in waze_data$Location) {
  pattern1 <- "Point(.*?) "
  pattern2 <- " (.*?))"

  x_coor <- regmatches(i, regexec(pattern1, i))
  x_temp <- x_coor[[1]][2] %>%
    substr(start=2, stop=99)
  #print(x_temp)
  x_fin <- rbind(x_fin, x_temp)
  y_coor <- regmatches(i, regexec(pattern2, i))
  y_temp <- y_coor[[1]][2]
  y_fin <- rbind(y_fin, y_temp)
}

x_fin$x_coor <- x_fin$X..106.598471.
y_fin$y_coor <- y_fin$X.31.911973.
waze_data$x_coor <- x_fin$x_coor
waze_data$y_coor <- y_fin$y_coor
```


```{r process waze jam data 2}
waze_sf <-
  waze_data %>%
  st_as_sf(coords = c("x_coor", "y_coor"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102339')

ggplot() +
  geom_sf(data = El_Paso_city, color="grey") +
  geom_sf(data = waze_sf, aes(colour=Subtype), size=0.5, show.legend = "point") +
  labs(title = "Waze jam data points by subtype",
       subtitle = "El Paso, TX") + mapTheme()

ggplot(waze_sf, aes(y=Subtype)) +
  geom_bar(width=0.5, color="transparent", fill = "#FF6666") +
  labs(title = "Waze jams numbers grouped by subtype",
       subtitle = "El Paso, TX") + plotTheme()
```


```{r process pot holes data to sf}
pot_holes_sf <-
  pot_holes %>%
  subset(WORKORDERID!=588771) %>%
  na.omit() %>%
  st_as_sf(coords = c("WOXCOORDINATE", "WOYCOORDINATE"),
           crs = 'epsg:2277',
           agr = "constant") %>%
  st_transform('ESRI:102339')

```


```{r grouping pot holes data by year}
pot_holes_sf$YEAR <- format(mdy_hms(pot_holes_sf$ACTUALFINISHDATE), format='%Y')
glimpse(pot_holes_sf)

pot_holes_sf <-
  pot_holes_sf %>%
  subset(YEAR != 1900)

# Clip to el paso city boundary
pot_holes_sf <-
  pot_holes_sf %>%
  st_intersection(El_Paso_city, pot_holes_sf)

pot_holes_sf$YEAR[pot_holes_sf$YEAR == 2106] <- 2016

# new sf with last five years of points data only for easier legibility on maps
pot_holes_sf_2015to2018 <- pot_holes_sf %>% dplyr::filter(YEAR > 2014 & YEAR < 2019)
pot_holes_sf_2019to2021 <- pot_holes_sf %>% dplyr::filter(YEAR > 2018)
pot_holes_sf_2018 <- pot_holes_sf %>% dplyr::filter(YEAR == 2018)
```


```{r 2018 streets and potholes map}
# 2018 map
ggplot() +
  geom_sf(data=EPCenterline, color="#585858", alpha=0.8) +
  geom_sf(data = pot_holes_sf_2018, size=0.2, color="blue", alpha=0.2) +
    geom_sf(data = El_Paso_city, fill="transparent", color="red") +
  guides(fill="legend")+
  labs(title = "Potholes and Centerlines in 2018",
       subtitle = "El Paso, TX") + mapTheme()
```


```{r lots of potholes maps}
# 2015-2018 map
ggplot() +
  geom_sf(data = El_Paso_city, fill="grey") +
  geom_sf(data = pot_holes_sf_2015to2018, aes(colour=YEAR), size=0.2, show.legend = "point") +
  labs(title = "Potholes in 2015-2018",
       subtitle = "El Paso, TX") + mapTheme()

#  2019-2021 map
ggplot() +
  geom_sf(data = El_Paso_city, fill="grey") +
  geom_sf(data = pot_holes_sf_2019to2021, aes(colour=YEAR), size=0.2, show.legend = "point") +
  labs(title = "Potholes 2019-2021",
       subtitle = "El Paso, TX") + mapTheme()

ggplot(pot_holes_sf, aes(y=YEAR)) +
  geom_bar(width=0.5, color="black", fill = "#FF6666") +
  labs(title = "Year of pot holes repairment",
       subtitle = "El Paso, TX") + plotTheme()

```


```{r zoning map}
# glimpse(zoning)

ggplot() +
  geom_sf(data = zoning, fill="grey") +
  labs(title = "Zoning",
       subtitle = "El Paso, TX") + mapTheme()
```


```{r EP center lines}
# delete duplicated "LOCAL" class first
# unique(EPCenterline$CLASS)

EPCenterline$CLASS[EPCenterline$CLASS == "LOCAL\r\n\r\n\r\n\r\n" | EPCenterline$CLASS == "LOCAL\r\n\r\n" | EPCenterline$CLASS == "LOCAL\r\n" | EPCenterline$CLASS == "LOCAL\r\n\r\n\r\n"] <- "LOCAL"
unique(EPCenterline$CLASS)

ggplot() +
  geom_sf(data = EPCenterline, aes(color = CLASS)) +
  labs(title = "Center lines with class",
       subtitle = "El Paso, TX") + mapTheme()

# unique(EPCenterline$CLASS)
ggplot(EPCenterline, aes(y=CLASS)) +
  geom_bar(width=0.5, color="black", fill = "#FF6666") +
  labs(title = "Pavement Center Lines by Class",
       subtitle = "El Paso, TX") + plotTheme()

```


```{r center_line}
# glimpse(center_line)

ggplot() +
  geom_sf(data = center_line, aes(color = PCI_2018)) +
  scale_color_viridis(direction=-1)+
  labs(title = "Street Centerlines with PCI 2018",
       subtitle = "El Paso, TX") + mapTheme()

# unique(center_line$PCI_2018)
ggplot(center_line, aes(y=PCI_2018)) +
  geom_bar(width=0.5, color="transparent", fill = "#FF6666") +
  labs(title = "PCI Distribution",
       subtitle = "El Paso, TX") + plotTheme()
```


```{r CIP_layer}
# glimpse(CIP_layer)

ggplot() +
  geom_sf(data = CIP_layer, aes(color = PCI)) +
  labs(title = "PCI data from CIP layer",
       subtitle = "El Paso, TX")

# unique(CIP_layer$PCI)
# unique(CIP_layer$DISTRICT)

```


```{r elpaso_pass}
# glimpse(elpaso_pass)

ggplot() +
  geom_sf(data = elpaso_pass, color = "red") +
  labs(title = "elpaso_pass",
       subtitle = "El Paso, TX")

ggplot(elpaso_pass, aes(y=pci_2018)) +
  geom_bar(width=0.5, color="transparent", fill = "#FF6666") +
  labs(title = "PCI distribution of Elpaso_pass",
       subtitle = "El Paso, TX")
```


```{r VMT data}
census_geom <-
  EP_census %>%
  subset(select = c("GEOID","geometry"))

# VMT <- read_csv("Data/ElPaso_VMT_res_bg.csv")

VMT$GEOID <- substr(VMT$FIPS, 1, 11)

VMT_sf <-
  census_geom %>%
  right_join(VMT, by="GEOID")

ggplot() +
  geom_sf(data = VMT_sf, aes(fill = count)) +
  labs(title = "VMT",
       subtitle = "El Paso, TX")

```

```{r tl_roads_data}
#comparing TIGER/Line shapefile to the street centerlines shapefile from Alex
tl_roads <- st_read("Data/tl_2018_roads/tl_2018_48141_roads.shp") %>%
  st_transform('ESRI:102339')

ggplot(tl_roads, aes(y=RTTYP)) +
  geom_bar(width=0.5, color="black", fill = "#FF6666") +
  labs(title = "El Paso,TX Roads by RouteType",
       subtitle = "TIGER/Line 2018")
```
