---
title: "fishnet"
author: "Sisun Cheng"
date: "2022/2/28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, results = FALSE, message = FALSE)
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

```{r create fishnet}
# create the fishnet and count the parking number
fishnet_sf <- 
  st_make_grid(El_Paso_city,
               cellsize = 500, 
               square = TRUE) %>%
  .[El_Paso_city] %>%           
  st_sf() %>%
  mutate(uniqueID = rownames(.))
```

```{r join waze data into fishnet}
# select the fishnet grids with waze jams
waze_net <- 
  dplyr::select(waze_sf) %>% 
  mutate(countJams = 1) %>% 
  aggregate(., fishnet_sf, sum) %>%
  mutate(countJams = replace_na(countJams, 0),
         uniqueID = rownames(.),
         cvID = sample(round(nrow(fishnet_sf) / 8), 
                       size=nrow(fishnet_sf), replace = TRUE)) %>%
  filter(countJams>0)


waze_net <-
  waze_net %>%
  dplyr::select(geometry, uniqueID, countJams)

```

```{r plot the waze net}
ggplot() +
  geom_sf(data = El_Paso_city, color = "grey") +
  geom_sf(data = waze_net, aes(fill = q5(countJams)), color = NA) +
  #geom_sf(data = fishnet_sf, fill = "transparent")+
  scale_fill_manual(values = palette_5,
                    labels = qBr(waze_net, "countJams"),
                    name = "Jam #")+
  labs(title = "Waze Jam Counts",
       subtitle = "El Paso, TX")+
  mapTheme()

ggplot(waze_net, aes(x=countJams)) + 
  geom_histogram(color="white", fill="#e6a52f", binwidth = 10) + 
  # scale_x_continuous(limits = c(1, 150)) +
  labs(title = "Distribution of Waze Jam Numbers in Fishnet",
       subtitle = "El Paso, TX") +
  plotTheme()
```


```{r join crash data into fishnet}
crash_net <- 
  dplyr::select(crash18_sf) %>% 
  mutate(countCrash = 1) %>% 
  aggregate(., fishnet_sf, sum) %>%
  mutate(countCrash = replace_na(countCrash, 0),
         uniqueID = rownames(.),
         cvID = sample(round(nrow(fishnet_sf) / 8), 
                       size=nrow(fishnet_sf), replace = TRUE)) %>%
  filter(countCrash>0)

crash_net <-
  crash_net %>%
  dplyr::select(geometry, uniqueID, countCrash)
```


```{r plot the crash net}
ggplot() +
  geom_sf(data = El_Paso_city, color = "grey") +
  geom_sf(data = crash_net, aes(fill = q5(countCrash)), color = NA) +
  scale_fill_manual(values = palette_5,
                    labels = qBr(crash_net, "countCrash"),
                    name = "Crash #")+
  labs(title = "Crash Counts",
       subtitle = "El Paso, TX")+
  mapTheme()

ggplot(crash_net, aes(x=countCrash)) + 
  geom_histogram(color="white", fill="#e6a52f", binwidth = 10) + 
  # scale_x_continuous(limits = c(1, 150)) +
  labs(title = "Distribution of Crash Numbers in Fishnet",
       subtitle = "El Paso, TX") +
  plotTheme()
```


```{r join potholes data into fishnet}
pothole_net <- 
  dplyr::select(potholes_sf) %>% 
  mutate(countPothole = 1) %>% 
  aggregate(., fishnet_sf, sum) %>%
  mutate(countPothole = replace_na(countPothole, 0),
         uniqueID = rownames(.),
         cvID = sample(round(nrow(fishnet_sf) / 8), 
                       size=nrow(fishnet_sf), replace = TRUE)) %>%
  filter(countPothole>0)

pothole_net <-
  pothole_net %>%
  dplyr::select(geometry, uniqueID, countPothole)
```


```{r plot the pothole net}
ggplot() +
  geom_sf(data = El_Paso_city, color = "grey") +
  geom_sf(data = pothole_net, aes(fill = q5(countPothole)), color = NA) +
  scale_fill_manual(values = palette_5,
                    labels = qBr(pothole_net, "countPothole"),
                    name = "Pothole #")+
  labs(title = "Pothole Counts",
       subtitle = "El Paso, TX")+
  mapTheme()

ggplot(pothole_net, aes(x=countPothole)) + 
  geom_histogram(color="white", fill="#e6a52f", binwidth = 10) + 
  # scale_x_continuous(limits = c(1, 150)) +
  labs(title = "Distribution of Pothole Numbers in Fishnet",
       subtitle = "El Paso, TX") +
  plotTheme()
```


```{r join three fishnet layers together}
all_net <-
  waze_net %>%
  merge(crash_net %>% st_drop_geometry()) %>%
  merge(pothole_net %>% st_drop_geometry())
```

## Interact with the centerline data layer

```{r load local centerline data}
test_centerline_with_age <- st_read("Data/PCI_Study/Centerline_with_Age.shp") %>%
  st_transform('ESRI:102339')

test_EPCenterline <- st_read("Data/Penn/EPCenterline.shp") %>%
  st_transform('ESRI:102339')
```


```{r EP centerlines, message=FALSE, warning=FALSE}
# delete duplicated "LOCAL" class
test_EPCenterline$CLASS[test_EPCenterline$CLASS == "LOCAL\r\n\r\n\r\n\r\n" | test_EPCenterline$CLASS == "LOCAL\r\n\r\n" | test_EPCenterline$CLASS == "LOCAL\r\n" | test_EPCenterline$CLASS == "LOCAL\r\n\r\n\r\n"] <- "LOCAL"

# remove some unneeded columns
# subset centerline data to El Paso city maintained segments
# Clip to el paso city boundary
test_EPCenterline <-
  test_EPCenterline %>%
  dplyr::select(-POD_ALIAS1, -POD_ALIAS2, -POD_ALIAS3, -POD_ALIAS4, -STS_ALIAS4 , -STN_ALIAS4, -PRD_ALIAS4 , -STS_ALIAS3, -PRD_ALIAS3, -STS_ALIAS2, -PRD_ALIAS2, -STS_ALIAS1, -PRD_ALIAS1, -STR, -STL, -ESNL, -ESNR) %>%
  subset(MUNR == 'CITY OF EL PASO') %>%
  st_intersection(El_Paso_city, test_EPCenterline) %>%
  subset(CLASS == "LOCAL" | CLASS == "MINOR" | CLASS == "MAJOR" | CLASS == "COLLECTOR" | CLASS == "MINOR PR" | CLASS == "COLLECTOR PR" | CLASS == "MAJOR PR" ) 

```


```{r prepare centerline data with PCI values from 2018, message=FALSE, warning=FALSE}
#join with centerline with age so we can include PCI info
test_EPCenterline_with_PCI <-
  test_EPCenterline %>%
  st_join(test_centerline_with_age)

# create an index so that each segment has a unique id
test_EPCenterline_with_PCI$index <- 1:nrow(test_EPCenterline_with_PCI)

test_EPCenterline_with_PCI <- 
  test_EPCenterline_with_PCI %>%
  subset(MUNR == 'CITY OF EL PASO') %>%
  st_intersection(El_Paso_city, test_EPCenterline_with_PCI)

```


```{r plot the correlations}
centerline_grid <-
  EPCenterline_new5 %>%
  st_join(all_net %>% 
            st_transform('ESRI:102339')) %>%
  dplyr::select(index, uniqueID, PCI_2018, countJams, countCrash, countPothole, 
                potholes_len, crash_len, waze_len) #%>%
  #na.omit()

EPCenterline_new6 <-
  EPCenterline_new5 %>%
  st_join(all_net %>% 
            st_transform('ESRI:102339'))

centerline_grid <-
  test_EPCenterline_with_PCI %>%
  st_join(all_net %>% 
            st_transform('ESRI:102339'))  %>%
  dplyr::select(index, PCI_2018, uniqueID, countJams, countCrash, countPothole, geometry) %>%
  na.omit()

centerline_grid_merge <-
  merge(EPCenterline_new5, st_drop_geometry(centerline_grid), by = "index", all.x=TRUE)

centerline_grid %>% 
  st_drop_geometry() %>%
  dplyr::select(PCI_2018, countJams, countCrash, countPothole, 
                potholes_len, crash_len, waze_len) %>%
  gather(Variable, Value, -PCI_2018) %>% 
  ggplot(aes(Value, PCI_2018)) +
  geom_point(size = 0.5, color = "grey") + 
  geom_smooth(method = "lm", se=F, colour = "#3FB0C0") +
     facet_wrap(~Variable, ncol = 3, scales = "free") +
     labs(title = "Numeric Variables vs. PCI",
          subtitle = "El Paso, TX") + 
  stat_cor(aes(label = ..r.label..), label.x = 0) +
  plotTheme()

```

## Amenities

```{r load amentiy data from outside source}
amenity <- read.csv("C:\\Users\\CSS\\Desktop\\MUSA801\\OSM_amenities\\OSM_amenity.csv")

amenity_sf <- 
  amenity %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102339')
```


```{r plot the amenities}
ggplot() +
  geom_sf(data = El_Paso_city, color = "grey") +
  geom_sf(data = amenity_sf, aes(color = amenity), size=0.5, show.legend = "point") +
  labs(title = "Open Street Map Amenities",
       subtitle = "El Paso, TX")+
  mapTheme()

ggplot(amenity_sf, aes(y=amenity)) +
  geom_bar(width=0.5, color="black", fill = "#08519c") +
  labs(title = "Amenities by Type",
       x="Count",
       y="Type",
       subtitle = "El Paso, TX") + plotTheme()
```

```{r divide amenities to different categories}
food_drink <- c('restaurant', 'fast_food', 'cafe', 'bar', 'ice_cream', 'pub')
entertainment <- c('arts_centre', 'cinema', 'theatre')
car_facility <- c('fuel', 'car_rental', 'car_wash', 'parking', 'parking_space')

am_food_drink <- amenity_sf %>%
  filter(amenity %in% food_drink)
am_entertainment <- amenity_sf %>%
  filter(amenity %in% entertainment)
am_car_facility <- amenity_sf %>%
  filter(amenity %in% car_facility)

```


```{r join the amenities to main df}
# KNN function
st_c <- st_coordinates
EP_test_KNN <-
  EPCenterline_new5 %>%
  mutate(
      food_drink_nn3 = nn_function(na.omit(st_c(st_centroid(EPCenterline_new5))),na.omit(st_c(am_food_drink)), 3),
      entertainment_nn3 = nn_function(na.omit(st_c(st_centroid(EPCenterline_new5))),na.omit(st_c(am_entertainment)), 3),
      car_facility_nn3 = nn_function(na.omit(st_c(st_centroid(EPCenterline_new5))),na.omit(st_c(am_car_facility)), 3),
  )


# fishnet again 
food_net <- 
  dplyr::select(am_food_drink) %>% 
  mutate(countFood = 1) %>% 
  aggregate(., fishnet_sf, sum) %>%
  mutate(countFood = replace_na(countFood, 0),
         uniqueID = rownames(.),
         cvID = sample(round(nrow(fishnet_sf) / 8), 
                       size=nrow(fishnet_sf), replace = TRUE)) %>%
  filter(countFood>0)


food_net <-
  food_net %>%
  dplyr::select(geometry, uniqueID, countFood)
```

```{r test correlation for PCI and knns}
EP_test_KNN %>% 
  st_drop_geometry() %>%
  dplyr::select(PCI_2018, food_drink_nn3, entertainment_nn3, car_facility_nn3) %>%
  gather(Variable, Value, -PCI_2018) %>% 
  ggplot(aes(Value, PCI_2018)) +
  geom_point(size = 0.5, color = "grey") + 
  geom_smooth(method = "lm", se=F, colour = "#3FB0C0") +
     facet_wrap(~Variable, ncol = 3, scales = "free") +
     labs(title = "Nearest Neighbor Variables vs. PCI",
          subtitle = "El Paso, TX") + 
  stat_cor(aes(label = ..r.label..), label.x = 0) +
  plotTheme()
```

## Modelling
```{r start with linear regression}
glimpse(EP_test_KNN)

OLS_reg1 <- 
  lm(PCI_2018 ~  crash_len + waze_count + potholes_len + 
       car_facility_nn3 + entertainment_nn3 + food_drink_nn3 + 
       road_age + VMT_pop + total_pop + n_hydro_int + 
       med_hh_income + pct_transport_to_work + pctWhite + 
       CLASS + land_use_type, 
     data = EP_test_KNN)

stargazer(OLS_reg1, type = "text",title = "OLS Regression Results", align=TRUE, no.space=TRUE)
summary(OLS_reg1)

EP_model_1 <-
  EP_test_KNN %>%
  mutate(PCI.Predict = predict(OLS_reg1, EP_test_KNN),
         PCI.Error = PCI.Predict - PCI_2018,
         PCI.AbsError = abs(PCI.Predict - PCI_2018),
         PCI.APE = (abs(PCI.Predict - PCI_2018)) / PCI.Predict) 

MAE <- mean(EP_model_1$PCI.AbsError, na.rm = T)
MAPE <- mean(EP_model_1$PCI.APE, na.rm = T)
acc <- data.frame(MAE, MAPE)
kable(acc) %>% 
  kable_styling(full_width = F)

```


```{r try poisson regression}
poisson_reg1 <- glm(formula = 
                      PCI_2018 ~  crash_len + waze_count + potholes_len + 
                       car_facility_nn3 + entertainment_nn3 + food_drink_nn3 + 
                       road_age + VMT_pop + total_pop + n_hydro_int + 
                       med_hh_income + pct_transport_to_work + pctWhite + 
                       CLASS + land_use_type, 
                    data = EP_test_KNN, 
                    family = poisson)
stargazer(poisson_reg1, type = "text",title = "Poisson Regression Results", align=TRUE, no.space=TRUE)

EP_model_2 <-
  EP_test_KNN %>%
  mutate(PCI.Predict = predict(poisson_reg1, EP_test_KNN),
         PCI.Error = PCI.Predict - PCI_2018,
         PCI.AbsError = abs(PCI.Predict - PCI_2018),
         PCI.APE = (abs(PCI.Predict - PCI_2018)) / PCI.Predict) 

MAE <- mean(EP_model_2$PCI.AbsError, na.rm = T)
MAPE <- mean(EP_model_2$PCI.APE, na.rm = T)
acc <- data.frame(MAE, MAPE)
kable(acc) %>% 
  kable_styling(full_width = F)

```

## Cross Validation

```{r k-fold cross validation for OLS model, warning=TRUE}
fitControl <- trainControl(method = "cv", number = 100)
set.seed(825)

OLS_reg1.cv <- 
  train(PCI_2018 ~  crash_len + waze_count + potholes_len + 
         car_facility_nn3 + entertainment_nn3 + food_drink_nn3 + 
         road_age + VMT_pop + total_pop + n_hydro_int + 
         med_hh_income + pct_transport_to_work + pctWhite + 
         CLASS + land_use_type, 
       data = EP_test_KNN,
        method = "lm", trControl = fitControl, na.action = na.pass)

OLS_reg1.cv
OLS_reg1.cv$resample[1:10,]
```


